### PR TITLE
0.1.4 - add addw2

### PR DESCRIPTION
**Pull request by jackpot51**
Rebase and tag when approved

### CODE REVIEW

**Comment by jackpot51** [comment]
@leviport please verify addw1 backlight functionality with this change

**Comment by leviport** [comment]
addw1 looks good on:
- [x] Pop 18.04
- [x] Pop 19.10
- [x] Pop 20.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04

**Comment by jackpot51** [comment]
@leviport building on all platforms now

**Review by mmstick — APPROVED** [review]

**Review by leviport — APPROVED** [review]

**Comment by leviport** [comment]
20.04 will have to be tested later

**Pull request merged**
